---
- name: second variable playbook test
  hosts: localhost
  
  tasks:
  - name: ensure httpd package is present
    yum:
      name: httpd
      state: latest
    register: httpd_results
    
  - name: restart httpd
    service:
      name: httpd
      state: restart
    when: httpd_results.changed
       