---
-name: install and start apache
hosts: web
become: yes

tasks:
  - name: httpd package is presente
    yum:
      name: httpd
      state: latest
      
  - name: latest index.html file s present
    template:
       src: files/index.html
       dest: /var/www/html
  - name: httpd is started
    service:
      name: httpd
      state: started