---
- name: third variable playbook-test handlers
  hosts: localhost
  
  tasks:
  - name: ensure httpd package is present
    yum:
      name: httpd
      state: latest
    notify: restart_httpd
    
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restart